"""Reproduce VG-vs-Direct scatter comparison on ReESH source holdout.

Trains two RF models on all non-ReESH observations, predicts on ReESH,
and plots side-by-side obs-vs-pred scatter panels.

This recreates the figure originally generated by the deleted
``map.learning.decision_tree.reesh_holdout`` module (vG branch, commit 463291b)
with corrected text rendering (R-squared superscript, proper units).

Usage:
    uv run python viz/presentation/fig_vg_vs_direct.py
    uv run python viz/presentation/fig_vg_vs_direct.py --output-dir figs/presentation
"""

import argparse
import re
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from swapstress.swrc import psi_from_theta

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

VG_PARAMS = ["theta_r", "theta_s", "alpha", "n"]

_EMBEDDING_PATTERNS = [
    re.compile(r"^embedding_\d+$"),
    re.compile(r"^e\d+$"),
    re.compile(r"^A\d+$"),
    re.compile(r"^b\d+$"),
    re.compile(r"^US_R3H3_"),
]

NON_FEATURE_COLS = {
    "theta_r",
    "theta_s",
    "alpha",
    "n",
    "Ks",
    "log10_alpha",
    "log10_n",
    "log10_Ks",
    "theta",
    "suction_cm",
    "log10_suction_cm",
    "sample_id",
    "profile_id",
    "station",
    "site_id",
    "obs_id",
    "source",
    "data_flag",
    "SWCC_class",
    "SWCC_classes",
    "data_ct",
    "nwsli_id",
    "network",
    "mesowest_i",
    "obs_ct",
    "MGRS_TILE",
    "lat",
    "lon",
    "latitude",
    "longitude",
    "rosetta_level",
    "depth_cm",
    "depth",
}

# ---------------------------------------------------------------------------
# Helpers (extracted from the deleted compare_approaches.py)
# ---------------------------------------------------------------------------


def _feature_cols(df: pd.DataFrame) -> list[str]:
    """Feature columns for the direct model (excludes targets/IDs/embeddings)."""
    cols = []
    for c in df.columns:
        if c in NON_FEATURE_COLS:
            continue
        if any(pat.match(c) for pat in _EMBEDDING_PATTERNS):
            continue
        cols.append(c)
    return sorted(c for c in set(cols) if df[c].notna().any())


def _blocking_features(df: pd.DataFrame, feature_cols: list[str]) -> list[str]:
    """Features that are >=99.99 % missing for any source."""
    blocking = []
    for col in feature_cols:
        if col not in df.columns:
            continue
        for src in df["source"].unique():
            if df.loc[df["source"] == src, col].isna().mean() >= 0.9999:
                blocking.append(col)
                break
    return blocking


def _train_rf(X, y, n_estimators=250, seed=42):
    rf = RandomForestRegressor(n_estimators=n_estimators, n_jobs=-1, random_state=seed)
    rf.fit(X, y)
    return rf


def _metrics(y_true, y_pred):
    mask = np.isfinite(y_true) & np.isfinite(y_pred)
    yt, yp = y_true[mask], y_pred[mask]
    return {
        "r2": r2_score(yt, yp),
        "rmse": float(np.sqrt(mean_squared_error(yt, yp))),
        "mae": mean_absolute_error(yt, yp),
        "bias": float(np.mean(yp - yt)),
        "n": int(mask.sum()),
    }


# ---------------------------------------------------------------------------
# Training / prediction
# ---------------------------------------------------------------------------


def run_holdout(obs_path: str, vg_path: str):
    """Train both models on non-ReESH data, return predictions on ReESH."""

    # --- load ---------------------------------------------------------------
    obs_df = pd.read_parquet(obs_path)
    obs_df = obs_df.dropna(subset=["lat", "lon"])
    print(f"Loaded {len(obs_df)} observations")

    train_obs = obs_df[obs_df["source"] != "reesh"].copy()
    test_obs = obs_df[obs_df["source"] == "reesh"].copy().reset_index(drop=True)
    print(f"  Train: {len(train_obs)}  Test (ReESH): {len(test_obs)}")

    # --- feature selection --------------------------------------------------
    feat = _feature_cols(train_obs)
    blocked = _blocking_features(train_obs, feat)
    feat = [f for f in feat if f not in set(blocked)]
    print(f"  {len(feat)} features after blocking filter")

    imputer = SimpleImputer(strategy="median")

    # --- direct model -------------------------------------------------------
    direct_feat = feat + ["theta"]
    X_train = imputer.fit_transform(train_obs[direct_feat].values)
    y_train = train_obs["log10_suction_cm"].values
    valid = ~np.isnan(y_train)
    rf_direct = _train_rf(X_train[valid], y_train[valid])
    print(f"  Direct RF trained on {valid.sum()} obs")

    X_test = imputer.transform(test_obs[direct_feat].values)
    y_pred_direct = rf_direct.predict(X_test)

    # --- VG model -----------------------------------------------------------
    vg_df = pd.read_parquet(vg_path)
    vg_train = vg_df[vg_df["source"] != "reesh"].copy()
    print(f"  VG train: {len(vg_train)} samples")

    # VG features — same set + rosetta_level (depth proxy)
    vg_feat = feat.copy()
    if "rosetta_level" in vg_train.columns:
        vg_feat.append("rosetta_level")
    vg_feat = sorted(set(vg_feat))

    vg_imputer = SimpleImputer(strategy="median")
    Xv_train = vg_imputer.fit_transform(vg_train[vg_feat].values)

    vg_models = {}
    for param in VG_PARAMS:
        y = vg_train[param].values.copy()
        if param == "alpha":
            y = np.where(y > 0, np.log10(y), np.nan)
        ok = ~np.isnan(y)
        vg_models[param] = _train_rf(Xv_train[ok], y[ok])
        print(f"  VG {param} RF trained on {ok.sum()} samples")

    # predict VG params for test obs
    Xv_test = vg_imputer.transform(test_obs[vg_feat].values)
    params = {}
    for param in VG_PARAMS:
        pred = vg_models[param].predict(Xv_test)
        if param == "alpha":
            pred = 10**pred
        params[param] = pred

    # se_eps=1e-10 is the clip this figure was produced with; it is deliberately
    # tighter than the PTF baseline's so the VG-inversion arm is shown at its
    # most favourable, not handicapped by a coarse guard.
    psi = psi_from_theta(
        test_obs["theta"].values,
        params["theta_r"],
        params["theta_s"],
        params["alpha"],
        params["n"],
        se_eps=1e-10,
    )
    y_pred_vg = np.log10(np.clip(psi, 1e-6, 1e10))

    y_true = test_obs["log10_suction_cm"].values
    return y_true, y_pred_direct, y_pred_vg


# ---------------------------------------------------------------------------
# Figure
# ---------------------------------------------------------------------------


def draw_panel(ax, y_true, y_pred, title):
    m = _metrics(y_true, y_pred)

    ax.scatter(y_true, y_pred, s=3, alpha=0.3, color="steelblue", edgecolors="none")

    lo = min(y_true.min(), y_pred.min()) - 0.2
    hi = max(y_true.max(), y_pred.max()) + 0.2
    ax.plot([lo, hi], [lo, hi], "k-", lw=0.8)
    ax.set_xlim(lo, hi)
    ax.set_ylim(lo, hi)
    ax.set_aspect("equal")

    ax.set_xlabel(r"Observed $\log_{10}(\psi)$ [cm H$_2$O]")
    ax.set_ylabel(r"Predicted $\log_{10}(\psi)$ [cm H$_2$O]")
    ax.set_title(title, fontsize=11, fontweight="bold")

    text = (
        f"$R^2$  = {m['r2']:.3f}\n"
        f"RMSE = {m['rmse']:.3f}\n"
        f"MAE  = {m['mae']:.3f}\n"
        f"Bias = {m['bias']:.3f}\n"
        f"n    = {m['n']}"
    )
    ax.text(
        0.05,
        0.95,
        text,
        transform=ax.transAxes,
        va="top",
        fontsize=9,
        family="monospace",
        bbox=dict(
            facecolor="white", alpha=0.85, edgecolor="0.6", boxstyle="round,pad=0.4"
        ),
    )
    return m


def make_figure(y_true, y_pred_direct, y_pred_vg, output_path: Path):
    plt.style.use("seaborn-v0_8-whitegrid")
    fig, (ax_direct, ax_vg) = plt.subplots(1, 2, figsize=(11, 5.5))

    m_direct = draw_panel(
        ax_direct, y_true, y_pred_direct, "Direct Model \u2014 ReESH Holdout"
    )
    m_vg = draw_panel(ax_vg, y_true, y_pred_vg, "VG Model \u2014 ReESH Holdout")

    fig.tight_layout(w_pad=3)
    fig.savefig(output_path, dpi=250, bbox_inches="tight")
    plt.close(fig)
    print(f"\nSaved figure to {output_path}")
    return m_direct, m_vg


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="VG vs Direct — ReESH holdout scatter")
    parser.add_argument(
        "--obs-table",
        default="/nas/soils/swapstress/training/obs_level_training_9km_global.parquet",
    )
    parser.add_argument(
        "--vg-table",
        default="/nas/soils/swapstress/training/obs_level_training_9km_global.parquet",
    )
    parser.add_argument("--output-dir", default="figs/presentation")
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    y_true, y_pred_direct, y_pred_vg = run_holdout(args.obs_table, args.vg_table)

    out_path = out_dir / "fig_vg_vs_direct_reesh.png"
    m_direct, m_vg = make_figure(y_true, y_pred_direct, y_pred_vg, out_path)

    print(f"\nDirect:  R2={m_direct['r2']:.4f}  RMSE={m_direct['rmse']:.4f}")
    print(f"VG:      R2={m_vg['r2']:.4f}  RMSE={m_vg['rmse']:.4f}")


if __name__ == "__main__":
    main()
