"""Supporting analysis: predicting suction directly against inverting van Genuchten.

Trains two RF models on all non-ReESH observations, predicts on ReESH, and
plots side-by-side obs-vs-pred scatter panels: the direct model that the
release ships, and the alternative that predicts van Genuchten parameters and
inverts the retention curve for suction.

This is the evidence behind the choice of target, so it backs the Methods text
rather than being one of the descriptor's Figs 1-6 -- ``swapstress-figures``
renders it on request, not as part of ``--figure all``. It still follows
``swapstress.figures.style``, so a supporting panel dropped beside a main
figure arrives in the same typeface at the same width.

This recreates the figure originally generated by the deleted
``swapstress.model.reesh_holdout`` module (vG branch, commit 463291b)
with corrected text rendering (R-squared superscript, proper units).

**This module trains five random forests** on the full observation table
before it draws anything; it is not a cheap re-render.

Usage:
    uv run swapstress-figures --figure vg-vs-direct
    uv run swapstress-figures --figure vg-vs-direct --output-dir figs/descriptor
"""

import argparse
import re
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from swapstress.figures import style
from swapstress.swrc import psi_from_theta

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

VG_PARAMS = ["theta_r", "theta_s", "alpha", "n"]

DEFAULT_OUTPUT_DIR = "figs/descriptor"

# Two square panels side by side. The height is what an equal-aspect pair needs
# at the double-column width once the shared axis labels are allowed for.
FIG_WIDTH_MM = style.DOUBLE_COLUMN_MM
FIG_HEIGHT_MM = 96.0

# The two estimators take the first two slots of the validated categorical
# palette, so each keeps the hue it has everywhere else in the figure set.
DIRECT_COLOR = style.CATEGORICAL[0]
VG_COLOR = style.CATEGORICAL[1]

_EMBEDDING_PATTERNS = [
    re.compile(r"^embedding_\d+$"),
    re.compile(r"^e\d+$"),
    re.compile(r"^A\d+$"),
    re.compile(r"^b\d+$"),
    re.compile(r"^US_R3H3_"),
]

NON_FEATURE_COLS = {
    "theta_r",
    "theta_s",
    "alpha",
    "n",
    "Ks",
    "log10_alpha",
    "log10_n",
    "log10_Ks",
    "theta",
    "suction_cm",
    "log10_suction_cm",
    "sample_id",
    "profile_id",
    "station",
    "site_id",
    "obs_id",
    "source",
    "data_flag",
    "SWCC_class",
    "SWCC_classes",
    "data_ct",
    "nwsli_id",
    "network",
    "mesowest_i",
    "obs_ct",
    "MGRS_TILE",
    "lat",
    "lon",
    "latitude",
    "longitude",
    "rosetta_level",
    "depth_cm",
    "depth",
}

# ---------------------------------------------------------------------------
# Helpers (extracted from the deleted compare_approaches.py)
# ---------------------------------------------------------------------------


def _feature_cols(df: pd.DataFrame) -> list[str]:
    """Feature columns for the direct model (excludes targets/IDs/embeddings)."""
    cols = []
    for c in df.columns:
        if c in NON_FEATURE_COLS:
            continue
        if any(pat.match(c) for pat in _EMBEDDING_PATTERNS):
            continue
        cols.append(c)
    return sorted(c for c in set(cols) if df[c].notna().any())


def _blocking_features(df: pd.DataFrame, feature_cols: list[str]) -> list[str]:
    """Features that are >=99.99 % missing for any source."""
    blocking = []
    for col in feature_cols:
        if col not in df.columns:
            continue
        for src in df["source"].unique():
            if df.loc[df["source"] == src, col].isna().mean() >= 0.9999:
                blocking.append(col)
                break
    return blocking


def _train_rf(X, y, n_estimators=250, seed=42):
    rf = RandomForestRegressor(n_estimators=n_estimators, n_jobs=-1, random_state=seed)
    rf.fit(X, y)
    return rf


def _metrics(y_true, y_pred):
    mask = np.isfinite(y_true) & np.isfinite(y_pred)
    yt, yp = y_true[mask], y_pred[mask]
    return {
        "r2": r2_score(yt, yp),
        "rmse": float(np.sqrt(mean_squared_error(yt, yp))),
        "mae": mean_absolute_error(yt, yp),
        "bias": float(np.mean(yp - yt)),
        "n": int(mask.sum()),
    }


# ---------------------------------------------------------------------------
# Training / prediction
# ---------------------------------------------------------------------------


def run_holdout(obs_path: str, vg_path: str):
    """Train both models on non-ReESH data, return predictions on ReESH."""

    # --- load ---------------------------------------------------------------
    obs_df = pd.read_parquet(obs_path)
    obs_df = obs_df.dropna(subset=["lat", "lon"])
    print(f"Loaded {len(obs_df)} observations")

    train_obs = obs_df[obs_df["source"] != "reesh"].copy()
    test_obs = obs_df[obs_df["source"] == "reesh"].copy().reset_index(drop=True)
    print(f"  Train: {len(train_obs)}  Test (ReESH): {len(test_obs)}")

    # --- feature selection --------------------------------------------------
    feat = _feature_cols(train_obs)
    blocked = _blocking_features(train_obs, feat)
    feat = [f for f in feat if f not in set(blocked)]
    print(f"  {len(feat)} features after blocking filter")

    imputer = SimpleImputer(strategy="median")

    # --- direct model -------------------------------------------------------
    direct_feat = feat + ["theta"]
    X_train = imputer.fit_transform(train_obs[direct_feat].values)
    y_train = train_obs["log10_suction_cm"].values
    valid = ~np.isnan(y_train)
    rf_direct = _train_rf(X_train[valid], y_train[valid])
    print(f"  Direct RF trained on {valid.sum()} obs")

    X_test = imputer.transform(test_obs[direct_feat].values)
    y_pred_direct = rf_direct.predict(X_test)

    # --- VG model -----------------------------------------------------------
    vg_df = pd.read_parquet(vg_path)
    vg_train = vg_df[vg_df["source"] != "reesh"].copy()
    print(f"  VG train: {len(vg_train)} samples")

    # VG features — same set + rosetta_level (depth proxy)
    vg_feat = feat.copy()
    if "rosetta_level" in vg_train.columns:
        vg_feat.append("rosetta_level")
    vg_feat = sorted(set(vg_feat))

    vg_imputer = SimpleImputer(strategy="median")
    Xv_train = vg_imputer.fit_transform(vg_train[vg_feat].values)

    vg_models = {}
    for param in VG_PARAMS:
        y = vg_train[param].values.copy()
        if param == "alpha":
            y = np.where(y > 0, np.log10(y), np.nan)
        ok = ~np.isnan(y)
        vg_models[param] = _train_rf(Xv_train[ok], y[ok])
        print(f"  VG {param} RF trained on {ok.sum()} samples")

    # predict VG params for test obs
    Xv_test = vg_imputer.transform(test_obs[vg_feat].values)
    params = {}
    for param in VG_PARAMS:
        pred = vg_models[param].predict(Xv_test)
        if param == "alpha":
            pred = 10**pred
        params[param] = pred

    # se_eps=1e-10 is the clip this figure was produced with; it is deliberately
    # tighter than the PTF baseline's so the VG-inversion arm is shown at its
    # most favourable, not handicapped by a coarse guard.
    psi = psi_from_theta(
        test_obs["theta"].values,
        params["theta_r"],
        params["theta_s"],
        params["alpha"],
        params["n"],
        se_eps=1e-10,
    )
    y_pred_vg = np.log10(np.clip(psi, 1e-6, 1e10))

    y_true = test_obs["log10_suction_cm"].values
    return y_true, y_pred_direct, y_pred_vg


# ---------------------------------------------------------------------------
# Figure
# ---------------------------------------------------------------------------


def draw_panel(ax, y_true, y_pred, letter, title, color, limits):
    m = _metrics(y_true, y_pred)

    # Rasterised marks only: the axes, the 1:1 line and every label stay
    # vector, which is what the artwork guide asks for.
    ax.scatter(
        y_true,
        y_pred,
        s=2.0,
        alpha=0.25,
        color=color,
        edgecolors="none",
        rasterized=True,
        zorder=2,
    )

    ax.plot(limits, limits, color="black", lw=0.6, dashes=(2.6, 1.8), zorder=3)
    ax.set_xlim(*limits)
    ax.set_ylim(*limits)
    ax.set_aspect("equal")

    ax.set_title(title, pad=2.5)
    style.panel_label(ax, letter, dx=-0.10, dy=1.02)

    ax.text(
        0.035,
        0.97,
        f"n = {m['n']:,}\n"
        f"RMSE = {m['rmse']:.3f}\n"
        f"MAE = {m['mae']:.3f}\n"
        f"bias = {m['bias']:+.3f}\n"
        f"R$^2$ = {m['r2']:+.3f}",
        transform=ax.transAxes,
        va="top",
        ha="left",
        fontsize=style.MAX_TEXT_PT - 1,
        linespacing=1.35,
        zorder=4,
        bbox=dict(facecolor="white", alpha=0.7, edgecolor="none", pad=1.2),
    )
    return m


def make_figure(y_true, y_pred_direct, y_pred_vg, output_dir: Path):
    """Draw both panels on one shared scale and write at the declared size."""
    style.apply()

    # One scale for both panels: the comparison is between the two estimators,
    # so a panel must not be able to look tighter by being drawn wider.
    stacked = np.concatenate([y_true, y_pred_direct, y_pred_vg])
    stacked = stacked[np.isfinite(stacked)]
    limits = (stacked.min() - 0.2, stacked.max() + 0.2)

    fig, (ax_direct, ax_vg) = plt.subplots(
        1,
        2,
        figsize=style.figsize(FIG_WIDTH_MM, FIG_HEIGHT_MM),
        sharex=True,
        sharey=True,
        layout="constrained",
    )

    m_direct = draw_panel(
        ax_direct,
        y_true,
        y_pred_direct,
        "a",
        "Direct suction model",
        DIRECT_COLOR,
        limits,
    )
    m_vg = draw_panel(
        ax_vg,
        y_true,
        y_pred_vg,
        "b",
        "van Genuchten parameters, inverted",
        VG_COLOR,
        limits,
    )

    ax_direct.set_ylabel(r"Predicted $\log_{10}$ suction (cm)")
    fig.supxlabel(r"Observed $\log_{10}$ suction (cm)", fontsize=style.MAX_TEXT_PT)
    fig.suptitle("ReESH source holdout", fontsize=style.MAX_TEXT_PT)

    path = style.save(fig, Path(output_dir) / "vg_vs_direct_reesh")
    print(f"\nSaved to {path}")
    return m_direct, m_vg


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Supporting analysis: direct suction model against inverted "
        "van Genuchten, on the ReESH source holdout. Trains five random forests."
    )
    parser.add_argument(
        "--obs-table",
        default="/nas/soils/swapstress/training/obs_level_training_9km_global.parquet",
    )
    parser.add_argument(
        "--vg-table",
        default="/nas/soils/swapstress/training/obs_level_training_9km_global.parquet",
    )
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args(argv)

    y_true, y_pred_direct, y_pred_vg = run_holdout(args.obs_table, args.vg_table)

    m_direct, m_vg = make_figure(
        y_true, y_pred_direct, y_pred_vg, Path(args.output_dir)
    )

    print(f"\nDirect:  R2={m_direct['r2']:.4f}  RMSE={m_direct['rmse']:.4f}")
    print(f"VG:      R2={m_vg['r2']:.4f}  RMSE={m_vg['rmse']:.4f}")


if __name__ == "__main__":
    main()
