"""
Shared, audited statistical machinery for the flux robustness re-test.

Pure functions, no I/O — every table in the re-test is generated by this one
module so the results survive review. See ``notes/flux_robustness_retest_plan.md``
§3 for the design rationale.

The central problem this module fixes: the previous flux validation reported
``psi_beyond_theta = R²(met+θ+ψ) − R²(met+θ)`` from *in-sample* nested OLS, a
quantity that is ≥ 0 at every site by construction (in-sample R² cannot fall
when a regressor is added). The one-sided Wilcoxon "median > 0" was therefore a
foregone conclusion. Everything here is out-of-sample (blocked cross-validation
with an embargo), permutation-calibrated (a block-permutation noise floor), or a
proper nested F-test — so "ψ adds beyond θ" can actually fail.

Contents
--------
- ``blocked_cv_r2`` / ``blocked_cv_metrics`` / ``blocked_cv_delta``
    Blocked cross-validation with a temporal embargo (§3.1).
- ``loyo_r2`` / ``loyo_delta``
    Leave-one-year-out cross-validation (§3.2).
- ``partial_f_test``
    Classic nested-model partial-F on the same rows (§3.3).
- ``block_permutation_null`` / ``permutation_p_value``
    Block-permutation noise floor for a ΔR² statistic (§3.4).
- ``site_bootstrap_ci`` / ``benjamini_hochberg`` / ``sign_test``
    Aggregation across sites and multiplicity control (§3.5).

All R² / skill values are "predictive R²": ``1 − SS_res / SS_tot`` where the
baseline is the *training* mean, so out-of-sample skill can be negative.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from scipy import stats as sp_stats

# ---------------------------------------------------------------------------
# Defaults (documented in the plan; overridable per call)
# ---------------------------------------------------------------------------
DEFAULT_N_BLOCKS = 5
DEFAULT_EMBARGO_DAYS = 15
DEFAULT_MIN_CV_DAYS = 150
DEFAULT_BLOCK_LEN = 30
DEFAULT_N_PERM = 200
DEFAULT_N_BOOT = 10000


# ---------------------------------------------------------------------------
# Low-level OLS
# ---------------------------------------------------------------------------


def _as_2d(X: np.ndarray) -> np.ndarray:
    X = np.asarray(X, dtype=np.float64)
    if X.ndim == 1:
        X = X.reshape(-1, 1)
    return X


def _ols_beta(X_design: np.ndarray, y: np.ndarray) -> np.ndarray | None:
    """Least-squares coefficients for a design matrix that already has an
    intercept column. Returns None if rank-deficient."""
    try:
        beta, _, rank, _ = np.linalg.lstsq(X_design, y, rcond=None)
    except np.linalg.LinAlgError:
        return None
    if rank < X_design.shape[1]:
        return None
    return beta


def _design(X: np.ndarray) -> np.ndarray:
    """Prepend an intercept column."""
    n = X.shape[0]
    return np.hstack([np.ones((n, 1), dtype=np.float64), X])


def _in_sample_ssr(X: np.ndarray, y: np.ndarray) -> float:
    """In-sample residual sum of squares for OLS with intercept (NaN if degenerate)."""
    X = _as_2d(X)
    Xd = _design(X)
    if Xd.shape[0] < Xd.shape[1] + 1:
        return np.nan
    beta = _ols_beta(Xd, y)
    if beta is None:
        return np.nan
    resid = y - Xd @ beta
    return float(resid @ resid)


def _fit_predict(X_train: np.ndarray, y_train: np.ndarray, X_test: np.ndarray):
    """Fit OLS (with intercept) on train, predict on test.

    Returns (y_hat_test, y_train_mean) or (None, None) if the fit is degenerate.
    """
    Xtr = _design(_as_2d(X_train))
    # Need at least one more row than parameters for a meaningful fit.
    if Xtr.shape[0] < Xtr.shape[1] + 1:
        return None, None
    beta = _ols_beta(Xtr, y_train)
    if beta is None:
        return None, None
    Xte = _design(_as_2d(X_test))
    return Xte @ beta, float(np.mean(y_train))


# ---------------------------------------------------------------------------
# Date handling
# ---------------------------------------------------------------------------


def _to_day_ordinals(dates) -> np.ndarray:
    """Convert an array of dates (datetime.date / Timestamp / datetime64 / str)
    to integer day ordinals."""
    idx = pd.to_datetime(pd.Index(list(dates)))
    return idx.values.astype("datetime64[D]").astype(np.int64)


def _to_years(dates) -> np.ndarray:
    idx = pd.to_datetime(pd.Index(list(dates)))
    return idx.year.to_numpy()


# ---------------------------------------------------------------------------
# §3.1 Blocked cross-validation with embargo
# ---------------------------------------------------------------------------


def blocked_fold_indices(
    dates,
    n_blocks: int = DEFAULT_N_BLOCKS,
    embargo_days: int = DEFAULT_EMBARGO_DAYS,
):
    """Contiguous time-block folds with an embargo buffer.

    Sorts rows by date, splits the time axis into ``n_blocks`` contiguous folds.
    For each fold the test set is the block; the train set is every row *outside*
    the block **and** outside an ``embargo_days`` buffer on both sides of the
    block's date range (so autocorrelation cannot leak across the boundary).

    Returns a list of ``(train_idx, test_idx)`` arrays of original-row indices.
    Folds with an empty test or train set are still returned (callers guard on
    fit feasibility); ordering follows the blocks in time.
    """
    ordinals = _to_day_ordinals(dates)
    order = np.argsort(ordinals, kind="stable")
    blocks = np.array_split(order, n_blocks)

    folds = []
    for block in blocks:
        if len(block) == 0:
            folds.append((np.array([], dtype=int), np.array([], dtype=int)))
            continue
        t_lo = ordinals[block].min()
        t_hi = ordinals[block].max()
        train_mask = (ordinals < t_lo - embargo_days) | (ordinals > t_hi + embargo_days)
        train_idx = np.where(train_mask)[0]
        folds.append((train_idx, np.asarray(block, dtype=int)))
    return folds


def _pooled_cv_metrics(
    X: np.ndarray,
    y: np.ndarray,
    folds,
    min_train: int,
) -> dict:
    """Accumulate out-of-sample SS pooled across folds.

    ``skill`` (primary) uses the *training* mean as the baseline so it can be
    negative; ``nse`` uses the pooled test mean; ``pearson_r2`` is the squared
    correlation of pooled predictions vs observations.
    """
    X = _as_2d(X)
    y = np.asarray(y, dtype=np.float64)

    ss_res = 0.0
    ss_tot_train = 0.0
    n_test_total = 0
    n_folds_used = 0
    obs_all, pred_all = [], []

    for train_idx, test_idx in folds:
        if len(test_idx) == 0 or len(train_idx) < min_train:
            continue
        y_hat, y_train_mean = _fit_predict(X[train_idx], y[train_idx], X[test_idx])
        if y_hat is None:
            continue
        y_test = y[test_idx]
        resid = y_test - y_hat
        ss_res += float(resid @ resid)
        base_resid = y_test - y_train_mean
        ss_tot_train += float(base_resid @ base_resid)
        obs_all.append(y_test)
        pred_all.append(y_hat)
        n_test_total += len(test_idx)
        n_folds_used += 1

    if n_folds_used == 0 or ss_tot_train < 1e-12:
        return {
            "skill": np.nan,
            "nse": np.nan,
            "pearson_r2": np.nan,
            "n_test": n_test_total,
            "n_folds": n_folds_used,
        }

    obs = np.concatenate(obs_all)
    pred = np.concatenate(pred_all)
    ss_tot_test = float(((obs - obs.mean()) ** 2).sum())
    skill = 1.0 - ss_res / ss_tot_train
    nse = 1.0 - ss_res / ss_tot_test if ss_tot_test > 1e-12 else np.nan
    if pred.std() > 1e-12 and obs.std() > 1e-12:
        r = np.corrcoef(pred, obs)[0, 1]
        pearson_r2 = float(r * r)
    else:
        pearson_r2 = np.nan

    return {
        "skill": float(skill),
        "nse": float(nse) if np.isfinite(nse) else np.nan,
        "pearson_r2": pearson_r2,
        "n_test": n_test_total,
        "n_folds": n_folds_used,
    }


def blocked_cv_metrics(
    X: np.ndarray,
    y: np.ndarray,
    dates,
    n_blocks: int = DEFAULT_N_BLOCKS,
    embargo_days: int = DEFAULT_EMBARGO_DAYS,
    min_cv_days: int = DEFAULT_MIN_CV_DAYS,
) -> dict:
    """Blocked-CV skill metrics for one predictor set (§3.1).

    Returns a dict with ``skill`` (out-of-sample R² vs the training mean),
    ``nse``, ``pearson_r2``, ``n_test`` and ``n_folds``. All-NaN if the site has
    fewer than ``min_cv_days`` rows or fewer than ``n_blocks`` populated folds.
    """
    X = _as_2d(X)
    y = np.asarray(y, dtype=np.float64)
    n = len(y)
    p = X.shape[1]
    nan_result = {
        "skill": np.nan,
        "nse": np.nan,
        "pearson_r2": np.nan,
        "n_test": 0,
        "n_folds": 0,
    }
    if n < min_cv_days:
        return nan_result

    folds = blocked_fold_indices(dates, n_blocks=n_blocks, embargo_days=embargo_days)
    min_train = p + 2
    metrics = _pooled_cv_metrics(X, y, folds, min_train=min_train)
    # Require every requested fold to be usable — otherwise the site is too
    # short / too gappy for a trustworthy CV estimate.
    if metrics["n_folds"] < n_blocks:
        return nan_result
    return metrics


def blocked_cv_r2(
    X: np.ndarray,
    y: np.ndarray,
    dates,
    n_blocks: int = DEFAULT_N_BLOCKS,
    embargo_days: int = DEFAULT_EMBARGO_DAYS,
    min_cv_days: int = DEFAULT_MIN_CV_DAYS,
) -> float:
    """Out-of-sample blocked-CV R² (skill) for one predictor set (§3.1)."""
    return blocked_cv_metrics(
        X,
        y,
        dates,
        n_blocks=n_blocks,
        embargo_days=embargo_days,
        min_cv_days=min_cv_days,
    )["skill"]


def blocked_cv_delta(
    X_reduced: np.ndarray,
    X_full: np.ndarray,
    y: np.ndarray,
    dates,
    n_blocks: int = DEFAULT_N_BLOCKS,
    embargo_days: int = DEFAULT_EMBARGO_DAYS,
    min_cv_days: int = DEFAULT_MIN_CV_DAYS,
) -> dict:
    """CV Δskill of the full model over the reduced model on *identical* folds.

    ``X_full`` should nest ``X_reduced`` (equal complexity is not required — the
    whole point of CV here is to compare models of *different* complexity fairly).
    Returns ``{skill_reduced, skill_full, delta, n_test, n_folds}``. Computing
    both skills on the same fold structure means the delta is matched row-for-row.
    """
    X_reduced = _as_2d(X_reduced)
    X_full = _as_2d(X_full)
    y = np.asarray(y, dtype=np.float64)
    n = len(y)
    nan_result = {
        "skill_reduced": np.nan,
        "skill_full": np.nan,
        "delta": np.nan,
        "n_test": 0,
        "n_folds": 0,
    }
    if n < min_cv_days:
        return nan_result

    folds = blocked_fold_indices(dates, n_blocks=n_blocks, embargo_days=embargo_days)
    min_train = X_full.shape[1] + 2
    red = _pooled_cv_metrics(X_reduced, y, folds, min_train=min_train)
    full = _pooled_cv_metrics(X_full, y, folds, min_train=min_train)
    if red["n_folds"] < n_blocks or full["n_folds"] < n_blocks:
        return nan_result
    return {
        "skill_reduced": red["skill"],
        "skill_full": full["skill"],
        "delta": full["skill"] - red["skill"],
        "n_test": full["n_test"],
        "n_folds": full["n_folds"],
    }


# ---------------------------------------------------------------------------
# §3.2 Leave-one-year-out CV
# ---------------------------------------------------------------------------


def _year_folds(years: np.ndarray):
    folds = []
    for yr in np.unique(years):
        test_idx = np.where(years == yr)[0]
        train_idx = np.where(years != yr)[0]
        folds.append((train_idx, test_idx))
    return folds


def loyo_r2(
    X: np.ndarray,
    y: np.ndarray,
    dates,
    min_years: int = 3,
) -> float:
    """Leave-one-year-out out-of-sample R² (§3.2). NaN if < ``min_years`` years."""
    X = _as_2d(X)
    y = np.asarray(y, dtype=np.float64)
    years = _to_years(dates)
    uniq = np.unique(years)
    if len(uniq) < min_years:
        return np.nan
    folds = _year_folds(years)
    metrics = _pooled_cv_metrics(X, y, folds, min_train=X.shape[1] + 2)
    if metrics["n_folds"] < min_years:
        return np.nan
    return metrics["skill"]


def loyo_delta(
    X_reduced: np.ndarray,
    X_full: np.ndarray,
    y: np.ndarray,
    dates,
    min_years: int = 3,
) -> dict:
    """LOYO Δskill of full over reduced on identical year folds (§3.2)."""
    X_reduced = _as_2d(X_reduced)
    X_full = _as_2d(X_full)
    y = np.asarray(y, dtype=np.float64)
    years = _to_years(dates)
    uniq = np.unique(years)
    nan_result = {
        "skill_reduced": np.nan,
        "skill_full": np.nan,
        "delta": np.nan,
        "n_test": 0,
        "n_folds": 0,
    }
    if len(uniq) < min_years:
        return nan_result
    folds = _year_folds(years)
    min_train = X_full.shape[1] + 2
    red = _pooled_cv_metrics(X_reduced, y, folds, min_train=min_train)
    full = _pooled_cv_metrics(X_full, y, folds, min_train=min_train)
    if red["n_folds"] < min_years or full["n_folds"] < min_years:
        return nan_result
    return {
        "skill_reduced": red["skill"],
        "skill_full": full["skill"],
        "delta": full["skill"] - red["skill"],
        "n_test": full["n_test"],
        "n_folds": full["n_folds"],
    }


# ---------------------------------------------------------------------------
# §3.3 Per-site nested partial-F
# ---------------------------------------------------------------------------


def partial_f_test(X_reduced: np.ndarray, X_full: np.ndarray, y: np.ndarray):
    """Classic nested-model partial-F test on the same rows (§3.3).

    Tests whether the extra regressors in ``X_full`` (which must nest
    ``X_reduced``) explain more variance than chance. Both models include an
    intercept.

    Returns ``(F, p, df1, df2)``; ``(nan, nan, df1, df2)`` if degenerate.
    """
    X_reduced = _as_2d(X_reduced)
    X_full = _as_2d(X_full)
    y = np.asarray(y, dtype=np.float64)
    n = len(y)

    p_red = X_reduced.shape[1]
    p_full = X_full.shape[1]
    df1 = p_full - p_red
    df2 = n - p_full - 1  # minus intercept
    if df1 < 1 or df2 < 1:
        return np.nan, np.nan, df1, df2

    ssr_red = _in_sample_ssr(X_reduced, y)
    ssr_full = _in_sample_ssr(X_full, y)
    if not (np.isfinite(ssr_red) and np.isfinite(ssr_full)):
        return np.nan, np.nan, df1, df2
    if ssr_full < 1e-12:
        return np.nan, np.nan, df1, df2

    f_stat = ((ssr_red - ssr_full) / df1) / (ssr_full / df2)
    if f_stat < 0:  # numerical: full should never fit worse than reduced
        f_stat = 0.0
    p_val = float(sp_stats.f.sf(f_stat, df1, df2))
    return float(f_stat), p_val, df1, df2


# ---------------------------------------------------------------------------
# §3.4 Block-permutation null (noise floor)
# ---------------------------------------------------------------------------


def circular_block_permute(x: np.ndarray, block_len: int, rng) -> np.ndarray:
    """Circularly shift then block-shuffle a 1-D series.

    Preserves short-range autocorrelation (within blocks of ``block_len``) but
    destroys the phase alignment with any paired response — the definition of a
    predictor "with the same autocorrelation but no true relationship."
    """
    x = np.asarray(x)
    n = len(x)
    if n <= 1 or block_len >= n:
        return x.copy()
    offset = int(rng.integers(0, n))
    rolled = np.roll(x, offset)
    starts = np.arange(0, n, block_len)
    blocks = [rolled[s : s + block_len] for s in starts]
    perm = rng.permutation(len(blocks))
    return np.concatenate([blocks[i] for i in perm])[:n]


def block_permutation_null(
    statistic_fn,
    predictor: np.ndarray,
    block_len: int = DEFAULT_BLOCK_LEN,
    n_perm: int = DEFAULT_N_PERM,
    seed: int = 0,
) -> np.ndarray:
    """Distribution of a ΔR² statistic under block-permuted predictors (§3.4).

    ``statistic_fn(perm_predictor) -> float`` recomputes the statistic (e.g. the
    ΔR² of adding this predictor) with the predictor block-permuted and the
    response left intact. The returned array is the noise floor: the gain
    attributable to a predictor with matched autocorrelation but no real signal.
    Use :func:`permutation_p_value` for the per-site permutation p and the
    null's mean/quantiles for the floor overlaid on figures.
    """
    rng = np.random.default_rng(seed)
    out = np.empty(n_perm, dtype=np.float64)
    for i in range(n_perm):
        perm = circular_block_permute(predictor, block_len, rng)
        try:
            out[i] = statistic_fn(perm)
        except Exception:
            out[i] = np.nan
    return out


def permutation_p_value(
    observed: float, null: np.ndarray, alternative: str = "greater"
) -> float:
    """Permutation p-value of ``observed`` against a ``null`` array.

    Uses the (b+1)/(m+1) estimator so p is never exactly 0.
    """
    null = np.asarray(null, dtype=np.float64)
    null = null[np.isfinite(null)]
    m = len(null)
    if m == 0 or not np.isfinite(observed):
        return np.nan
    if alternative == "greater":
        b = int(np.sum(null >= observed))
    elif alternative == "less":
        b = int(np.sum(null <= observed))
    else:
        b = int(np.sum(np.abs(null) >= abs(observed)))
    return (b + 1) / (m + 1)


# ---------------------------------------------------------------------------
# §3.5 Aggregation & multiplicity
# ---------------------------------------------------------------------------


def site_bootstrap_ci(
    values,
    n_boot: int = DEFAULT_N_BOOT,
    alpha: float = 0.05,
    statistic=np.median,
    seed: int = 0,
):
    """Bootstrap CI for a statistic over site-level values (§3.5).

    Resamples *sites* (the independent unit) with replacement. Returns
    ``(point, lo, hi)`` where ``point`` is the statistic on the observed values
    and ``lo/hi`` are the (alpha/2, 1-alpha/2) percentiles of the bootstrap
    distribution. All-NaN if fewer than 3 finite values.
    """
    values = np.asarray(values, dtype=np.float64)
    values = values[np.isfinite(values)]
    n = len(values)
    if n < 3:
        return np.nan, np.nan, np.nan
    rng = np.random.default_rng(seed)
    point = float(statistic(values))
    boot = np.empty(n_boot, dtype=np.float64)
    for i in range(n_boot):
        sample = values[rng.integers(0, n, size=n)]
        boot[i] = statistic(sample)
    lo = float(np.percentile(boot, 100 * alpha / 2))
    hi = float(np.percentile(boot, 100 * (1 - alpha / 2)))
    return point, lo, hi


def benjamini_hochberg(pvals, alpha: float = 0.05):
    """Benjamini–Hochberg FDR control (§3.5).

    Returns ``(rejected_mask, adjusted_pvals)`` aligned to the input order.
    NaN p-values are never rejected and pass through as NaN adjusted values.
    """
    pvals = np.asarray(pvals, dtype=np.float64)
    n_total = len(pvals)
    rejected = np.zeros(n_total, dtype=bool)
    adjusted = np.full(n_total, np.nan, dtype=np.float64)

    finite_idx = np.where(np.isfinite(pvals))[0]
    m = len(finite_idx)
    if m == 0:
        return rejected, adjusted

    p = pvals[finite_idx]
    order = np.argsort(p, kind="stable")
    ranked = p[order]
    ranks = np.arange(1, m + 1)

    # Adjusted p-values (step-up), enforced monotone non-decreasing.
    adj_sorted = ranked * m / ranks
    adj_sorted = np.minimum.accumulate(adj_sorted[::-1])[::-1]
    adj_sorted = np.clip(adj_sorted, 0.0, 1.0)

    adj = np.empty(m, dtype=np.float64)
    adj[order] = adj_sorted
    adjusted[finite_idx] = adj

    # Rejection: largest k with p_(k) <= k/m * alpha.
    below = np.where(ranked <= ranks / m * alpha)[0]
    if len(below) > 0:
        k_max = below.max()
        reject_sorted = np.zeros(m, dtype=bool)
        reject_sorted[: k_max + 1] = True
        rej = np.empty(m, dtype=bool)
        rej[order] = reject_sorted
        rejected[finite_idx] = rej
    return rejected, adjusted


def sign_test(values, popmean: float = 0.0, alternative: str = "greater") -> dict:
    """Binomial sign test that per-site values exceed ``popmean`` (§3.3/§3.5).

    Reports the fraction of positive deltas and a binomial p-value vs the 50%
    (or, for the partial-F-rate use case, an explicit chance rate via
    :func:`binomial_rate_test`).
    """
    values = np.asarray(values, dtype=np.float64)
    values = values[np.isfinite(values)]
    n = len(values)
    if n == 0:
        return {"n": 0, "frac_pos": np.nan, "p": np.nan}
    n_pos = int(np.sum(values > popmean))
    n_effective = int(np.sum(values != popmean))
    if n_effective == 0:
        return {"n": n, "frac_pos": 0.0, "p": 1.0}
    res = sp_stats.binomtest(n_pos, n_effective, p=0.5, alternative=alternative)
    return {"n": n, "frac_pos": n_pos / n, "p": float(res.pvalue)}


def binomial_rate_test(
    n_success: int, n_trials: int, rate: float = 0.05, alternative: str = "greater"
) -> float:
    """Binomial test that ``n_success/n_trials`` exceeds a chance ``rate`` (§3.3).

    Used for "fraction of sites with per-site partial-F significant, vs the 5%
    chance rate."
    """
    if n_trials == 0:
        return np.nan
    res = sp_stats.binomtest(n_success, n_trials, p=rate, alternative=alternative)
    return float(res.pvalue)


def wilcoxon_greater(values) -> float:
    """One-sided Wilcoxon signed-rank p that the median of ``values`` > 0.

    Kept for parity with the legacy tables (reported *alongside* the CV/perm
    tests, never as the sole evidence)."""
    values = np.asarray(values, dtype=np.float64)
    values = values[np.isfinite(values)]
    if len(values) < 5:
        return np.nan
    try:
        _, p = sp_stats.wilcoxon(values, alternative="greater")
    except ValueError:
        return np.nan
    return float(p)
